domain: "text.openfx.no"
url: "https://text.openfx.no"
title: "TextOFX"
description: "Advanced text generator for motion graphics and VFX software using the OpenFX standard published by the Academy Software Foundation."
header: "assets/images/textofx-header-002.jpg"
meta: "assets/images/textofx-header-001-290.png"
author:
  title: "Ole-Andr√© Rodlie"
  url: "https://github.com/rodlie"
company:
  title: "NettStudio AS"
  url: "https://nettstudio.no"
permalink: /:categories/:title:output_ext
